name: 2) Build and deploy to Scaleway

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Bump version in package.json file
        run: |
          sed -i 's/"version": "\([^#]*\)",/"version": "${{ github.ref_name }}",/g' package.json
      - uses: EndBug/add-and-commit@v9
        with:
          message: Bump version to ${{ github.ref_name }}
          push: origin HEAD:master

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: stockmarketpredictionsfront
          tags: ${{ github.ref_name }}
          registry: rg.fr-par.scw.cloud/funcscwstockmarketpredictiocvxl0lfn
          directory: public
          dockerfile: public/Dockerfile
          username: ${{ secrets.SCW_ACCESS_KEY }}
          password: ${{ secrets.SCW_SECRET_TOKEN }}

      - name: Patch Scaleway Serverless container front
        uses: wei/curl@v1
        with:
          args: --location --request PATCH https://api.scaleway.com/containers/v1beta1/regions/fr-par/containers/3dbe3a9e-3329-45de-98ef-479424641d35 --header 'X-Auth-Token:${{ secrets.SCW_SECRET_TOKEN }}' --header 'Content-Type:application/json' --data-raw '{\"registry_image\":\"rg.fr-par.scw.cloud/funcscwstockmarketpredictiocvxl0lfn/stockmarketpredictionsfront:${{ github.ref_name }}\"}'

      - name: Deploy Scaleway Serverless container front
        uses: wei/curl@v1
        with:
          args: --location --request POST https://api.scaleway.com/containers/v1beta1/regions/fr-par/containers/3dbe3a9e-3329-45de-98ef-479424641d35/deploy --header 'X-Auth-Token:${{ secrets.SCW_SECRET_TOKEN }}' --header 'Content-Type:application/json' --data-raw '{}'